CREATE TABLE IF NOT EXISTS `hotel`(
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(25) NOT NULL,
	`location_id` INT(11) NOT NULL,
	`description` LONGTEXT NULL,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`),
	CONSTRAINT `FK_hotel_location` FOREIGN KEY (`location_id`) REFERENCES `location`(`id`)
	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;