CREATE TABLE IF NOT EXISTS `payment`(
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` INT (11) NOT NULL,
	`amount` DECIMAL (10,2) DEFAULT 0,
	`status` VARCHAR(50) NOT NULL,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	CONSTRAINT `FK_payment_user` FOREIGN KEY (`user_id`) REFERENCES `users`(id)
)	ENGINE=InnoDB DEFAULT CHARSET=utf8;