CREATE TABLE IF NOT EXISTS `passenger_ticket`(
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`passenger_name` VARCHAR(100) NOT NULL,
	`email` VARCHAR(64) NOT NULL,
	`phone_number` VARCHAR(15) NOT NULL,
	`ticket_number` VARCHAR(13) NOT NULL,
	`seat_no` VARCHAR(10) NOT NULL,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;