CREATE TABLE IF NOT EXISTS `resources`(
`id` VARCHAR(36) NOT NULL,
`value` VARCHAR(255) NOT NULL,
`timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;