CREATE TABLE IF NOT EXISTS `company`(
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(36) NOT NULL,
	`rating` DECIMAL(2,1) DEFAULT 0,
	`company_logo` VARCHAR(36) DEFAULT NULL,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`),
	CONSTRAINT `company_picture` FOREIGN KEY (`company_logo`) REFERENCES `picture`(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;